### ISSUE TITLE
When advisor changes course state, it shows new badge but it shouldn't.

### ISSUE THREAD

**Issue by nihesh7391** [s-gv/bheemboy#103]

**Comment by s-gv** [comment]
I can't reproduce this. Please describe the steps that lead to this bug.

**Comment by rajeshsundaresan** [comment]
Try this. This was one of the examples where we saw during the demo today.

Student requests crediting a course, adviser marks as read, instructor marks as read, dcc approves, then student requests credit-to-audit change, and adviser rejects the change. At this stage, a refresh continues to keep the 'new' label until adviser marks its as read.

Desired: once adviser rejects change, get back to previous state, but don't label as 'new'.
