### ISSUE TITLE
Delete advisor deletes all students associated with advisor

### ISSUE THREAD

**Issue by rajeshsundaresan** [s-gv/bheemboy#107]
I am not sure if this is a bug. 

I deleted an advisor, Parimal Parag, because there were duplicate items. All students under him also got deleted. Does delete advisor delete the associated students as well?

Can a student be created without an associated advisor? If yes, the above is a bug. If not, it's fine.

**Comment by s-gv** [comment]
Adviser field cannot be empty for students. And yes, deletes cascade through tables.

If there are duplicate entries in any table (users, degrees, etc.), use the "merge selected objects" action.
