### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by nihesh7391** [s-gv/bheemboy#18]
Create an faq page..

**Comment by s-gv** [comment]
I've added a table for FAQs and a command line tool to bulk load FAQs from a file. FAQs can now be viewed by students. A similar view should be added for faculty as well.

**Comment by vinkumbr** [comment]
FAQ page for the faculty has been written. The profile tab for the faculty needs to be done.

**Comment by s-gv** [comment]
Bug - hitting the FAQ button on the faculty page for approving courses takes the faculty to the student FAQ rather than the faculty FAQ!

**Comment by nihesh7391** [comment]
Bug fixed!!
