### ISSUE TITLE
How do you like this name?

### ISSUE THREAD

**Issue by s-gv** [s-gv/bheemboy#20]
The name Bheem is more evocative of power than learning. How do you guys like the name 'Eklavya'? 

Leave a comment on which name you like (or propose another name).

**Comment by vinkumbr** [comment]
Well 'Eklavya' was a student who was not allowed to officially register..... We might even have to give up our thumbs trying to mount it on the CSA Drona server. Jokes apart it is actually decent. I was thinking more like 'Gurukul' or 'Nalanda' or 'Taxila'..

**Comment by arthi-ramaniam** [comment]
Adding a few more suggestions CreditCard, CourseBook, Ticker (related to share market, when there is a  list of shares listed).

**Comment by rajeshsundaresan** [comment]
What's in a name? That which we call a rose by any other name would smell as sweet. So would Bheemboy would, were it not Bheemboy called.

**Comment by arthi-ramaniam** [comment]
Bheemboy lives.
