### ISSUE TITLE
Merge changes correctly

### ISSUE THREAD

**Issue by s-gv** [s-gv/bheemboy#21]
Notice that several of my changes were deleted by @arthi-ramaniam in the commit 39d99dbac4da2520c7d1c6136bd326dd985703a1

Please exercise more caution when merging your changes.

**Comment by rajeshsundaresan** [comment]
Please follow this sequence: checkout, lock repository, view the result of merge in your local directory and resolve conflicts, verify, check-in, and then release the lock on the repository.

Please resolve ALL conflicts before check-in of your code.

Is there a list of tests that we could run (to ascertain correct regression) before pushing code into the repository?

**Comment by s-gv** [comment]
Currently there are no tests.

**Comment by arthi-ramaniam** [comment]
Is it in view.py? Or admin.py also is affected?

**Comment by arthi-ramaniam** [comment]
We are presently using separate branches before merging. Closing this issue.
