### ISSUE TITLE
How about allowing the adviser to directly add courses?

### ISSUE THREAD

**Issue by s-gv** [s-gv/bheemboy#22]
Scenario: Student thinks of what courses to take and applies for them via the website and then meets the adviser. They discuss and decide that the student should take a different course. Rather than asking the student to re-apply, how about allowing the adviser to add the course for the student right there?

**Comment by parimalparag** [comment]
This is an interesting feature. However, we should look at this after the top priority features have been added.

**Comment by rajeshsundaresan** [comment]
I too suggest that we keep it simple: student proposes, advisor approves.

**Comment by arthi-ramaniam** [comment]
Closing it. As we are not implementing it as of now.
