### ISSUE TITLE
Email alerts to Instructor and Advisor

### ISSUE THREAD

**Issue by arthi-ramaniam** [s-gv/bheemboy#25]
Periodic email alerts for instructor and advisor to approve requests

**Comment by rajeshsundaresan** [comment]
Don't make this periodic. Instead provide a trigger on DCC chair's page.

**Comment by bhargavajs07** [comment]
Waiting for the DCC chair page (issue #17) to be completely checked into integrate this feature on DCC chair's page.
Currently the set up seems to be broken as views/dcc.py that wasn't checked in.

**Comment by bhargavajs07** [comment]
Checked in the changes to send the email alerts. Could add real users(with valid mail-ids) to the portal to test out this feature.
