### ISSUE TITLE
Students approved by the course instructor disappear (temporarily)

### ISSUE THREAD

**Issue by s-gv** [s-gv/bheemboy#29]
When a course instructor approves a student for the course, the approved student is removed from the list and is not shown as an enrolled student until DCC approval. It feels weird to see students that I just approved drop off the list. I think approved students pending only DCC approval should be listed as enrolled. This will also help the course instructors to keep track of how many students they have approved for the course.

**Comment by nihesh7391** [comment]
Bug is fixed!!!
