### ISSUE TITLE
Create a Light weight system admin page.

### ISSUE THREAD

**Issue by bhargavajs07** [s-gv/bheemboy#3]
Create a Light weight system admin page, that allows the system admin a restricted access to the database and an easier view for the system admin's functions.

The sys admin page must contain easy way to 
1. Add new users, --> Perhaps a CSV upload feature (if they are currently using excel)?
2. Add new courses. and assign instructors to the courses.
3. Create in bulk, new instances of courses that were offered in the past semesters.
4. Reset user passwords on request.

**Comment by s-gv** [comment]
For bulk creating courses, we can create an admin action (similar to the delete multiple users option in the dropdown menu in the admin page) that copies selected courses from the last year.

**Comment by arthi-ramaniam** [comment]
True. Regarding bulk user upload, is nihesh or vinay working on it? I vaguely remember one of you working on it. If not, I shall start.

**Comment by s-gv** [comment]
I'll do the course cloning in the `/sudo` interface.

**Comment by s-gv** [comment]
Django does support extending the admin interface: https://docs.djangoproject.com/en/dev/ref/contrib/admin/#overriding-admin-templates

**Comment by arthi-ramaniam** [comment]
Not implementing admin page as of now. Closing it.
