### ISSUE TITLE
Course page- Faculty

### ISSUE THREAD

**Issue by vinkumbr** [s-gv/bheemboy#31]
In the course page, the names of students who have been 'Advisor Rejected' or 'Instructor rejected' are also displayed on the Enrolled students section. It should only list those who have been 'Instructor approved' or 'DCC approved'

**Comment by vinkumbr** [comment]
Feature added. Enrolled students are either 'Instructor approved' or 'DCC approved'. Is it necessary to display the students who the instructor has rejected??

**Comment by bhargavajs07** [comment]
I think we should not display the students that were rejected by instructor in the enrolled students list.

**Comment by vinkumbr** [comment]
I meant should we have a separate list of rejected students?

**Comment by nihesh7391** [comment]
What about drop? If a student drops a course, his name should be displayed or not? 
I guess, it is better to have another list which says rejected students/ students who dropped the course..

**Comment by arthi-ramaniam** [comment]
As of now, we dont need it as a functionality, I think. The details are available in the participant table. In case instructor/adviser/DCC needs this info, they can get it.

**Comment by rajeshsundaresan** [comment]
Once Instructor rejects, the course should still show in advisor and student's page as "Instructor rejected". Student should then 'cancel' the course (doesn't need advisor approval). Once student cancels, the course registration attempt is removed from the database.

**Comment by rajeshsundaresan** [comment]
We will inform DCC not to approve in such cases. Send it back to the student to delete the rejected courses.
