### ISSUE TITLE
POST request is made when DCC clicks on a student

### ISSUE THREAD

**Issue by s-gv** [s-gv/bheemboy#37]
It seems to me that when the DCC clicks on a student, it should do a HTTP GET because the server isn't modified. But a POST request is being made with a form. Please check if this is intentional.

**Comment by s-gv** [comment]
Preferably, the student name should be a link. Is there any reason for making it a form and styling it as a link?

This matters because if the DCC hits the refresh button when viewing a student's courses, the browser asks if the POST request should be repeated. This is confusing and doesn't make much sense because it feels like the no data was submitted to the server, but the browser asks if it should re-submit the data.

**Comment by nihesh7391** [comment]
Now, it has been modified to HTTP GET.
