### ISSUE TITLE
Faculty views do not follow Post/Redirect/Get pattern

### ISSUE THREAD

**Issue by s-gv** [s-gv/bheemboy#39]
In the advisees page for faculty, the student names are not links but forms that POST. This leads to poor user experience when the faculty clicks on a student and then hits the refresh button in the browser. A confusing dialog box asking if the user wishes re-submit the form data appears. 

For actions that do not modify the state of the server, use HTTP GET (preferably a simple link). If it does modify the server (like approving a course for a student), then do a [POST / REDIRECT / GET](https://en.wikipedia.org/wiki/Post/Redirect/Get). Do _not_ render the result of the action after POSTing without a redirect.

Notice that the same issue happens when the adviser approves a course and then hits the refresh button.

**Comment by vinkumbr** [comment]
now faculty views follow Post/Redirect/Get method....
