### ISSUE TITLE
DCC can approve individual courses

### ISSUE THREAD

**Issue by s-gv** [s-gv/bheemboy#41]
I was under the impression that DCC approval is all / nothing. So, allowing the DCC to approve individual courses looks like an anti-feature.

**Comment by nihesh7391** [comment]
This needs to be discussed...
This has been added for ease of student..
Suppose, a student requests more credits then he/she is allowed. In this case, student has to go back and cancel one or more courses.. Instead, DCC can accept few courses and reject others...

**Comment by rajeshsundaresan** [comment]
It should all or none.

**Comment by nihesh7391** [comment]
Yes.. Implemented it current push!!!
