### ISSUE TITLE
Course remains in crediting state with "DCC approved audit conversion"

### ISSUE THREAD

**Issue by s-gv** [s-gv/bheemboy#44]
Is there anything to be done after the DCC approves credit to audit conversion? Shouldn't the course me marked as audit? Also, is the DCC approval needed for conversion, or does advisor approval suffice?

**Comment by bhargavajs07** [comment]
For credit to audit conversion or audit to credit conversion, is DCC approval required or is adviser approval sufficient?

Currently,there are 2 issues:
1. The conversion requests are not appearing on DCC's  active requests page for DCC to approve or reject.
2. The states are not changing after adviser's approval.

I want to know the intended flow whether to include DCC's approval or just update the enrolment type on adviser's approval.

**Comment by arthi-ramaniam** [comment]
DCC approval is needed for Audit to Credit or vice versa conversion. It needs to be listed in.

**Comment by arthi-ramaniam** [comment]
Added DCC approval for A/C and vice versa. Also for drop. 
Once A/C is approved, student status changes to "Final State Approved".
A/C updated in participant table. 
Once dropped, status changes to "DCC approved drop".
