### ISSUE TITLE
Separate tables for crediting and auditing students in the instructor page

### ISSUE THREAD

**Issue by s-gv** [s-gv/bheemboy#46]

**Comment by rajeshsundaresan** [comment]
In the Instructor's, Enrollment type should be indicated. Also, we should see partitioned tables with headings Student Enrollment Requests, Crediting Students, Auditing Students, Dropped Students.

In the DCC's, Instructor's, Advisor's page, we should see the Enrollment Type.

**Comment by nihesh7391** [comment]
Implemented
