### ISSUE TITLE
Admin Page

### ISSUE THREAD

**Issue by nihesh7391** [s-gv/bheemboy#5]
While adding faculty position, remove displaying adviser, program and Sr.No fields.

**Comment by s-gv** [comment]
This will need client-side JS to monitor whether the user_type selected is a student or faculty and to hide the adviser/program/sr_no fields when faculty is chosen. This is potentially brittle code that could break if a future version of django changes the field names in the form. 

I don't see any simple way of doing this.

**Comment by arthi-ramaniam** [comment]
I ve also created an admin page

**Comment by s-gv** [comment]
I dont think we need to build a custom admin interface. It seems like a lot of work for more or less replicating the django admin interface.

**Comment by arthi-ramaniam** [comment]
I ve created a basic user add page. In the django admin page, can we make some fields optional and some fields mandatory? (For ex, advisor id/SRNo is mandatory for students). Do we have to drop page?

**Comment by s-gv** [comment]
We can make fields optional / mandatory. But I don't any easy way of dynamically changing this based on the user_type chosen in the dropdown.

**Comment by vinkumbr** [comment]
Hey
   I am unable to run the server on my local machine as it is giving me this error. I am using the code which I pulled from here. I feel there is an error in the admin page. Could you please have a look into it?
  File "/home/vinay/courseRegrWebSite/bheemboy/bheemboy/coursereg/admin.py", line 7, in <module>
    from dateutil.relativedelta import relativedelta
ImportError: No module named dateutil.relativedelta

Also which version is running on the server at 10.32.33.70?

**Comment by rajeshsundaresan** [comment]
This is a cosmetic feature. We will reconsider this issue when we implement the lightweight admin page.
