### ISSUE TITLE
DCC reject is now Meet DCC

### ISSUE THREAD

**Issue by rajeshsundaresan** [s-gv/bheemboy#50]
DCC will approve all or say "Meet DCC". Add a remarks box. This should be visible to Student and DCC.

If "Meet DCC", then student can make changes (cancel with advisor approval), add new course as per usual work flow. 

Once DCC approves, wipe out the data entered in the remarks box.

**Comment by nihesh7391** [comment]
Added remarks box for DCC!! Remarks are visible to student, adviser and DCC. Only DCC can modify the remark..
Student can cancel a course any time prior to DCC approval.. Of course, adviser has to approve it.
Once DCC approves it, remarks are wiped out from the database.

**Comment by bhargavajs07** [comment]
Added code to Send email to student to meet DCC.

**Comment by rajeshsundaresan** [comment]
Change layout.
Text box for "DCC's remarks".
Redisplay previous comments in the text box, ready to accept further modifications.
Show two buttons -- Approve or Meet me.

**Comment by nihesh7391** [comment]
Implemented!!
