### ISSUE TITLE
Student can masquerade as faculty/ DCC and self-approve

### ISSUE THREAD

**Issue by vinkumbr** [s-gv/bheemboy#55]
Authentication and Authorization mechanisms needs to be strengthened since if a student gets to know the url of any faculty page, then he would be able to manipulate the databases as an instructor.

Similar issues are true where one instructor can manipulate data of another instructor's students.

**Comment by bhargavajs07** [comment]
Added the checks to the dcc.py to ensure only user who is a dcc of the corresponding department can run the tasks in the dcc.py file.

**Comment by bhargavajs07** [comment]
Similar checks may be added to the instructor and faculty .py files to check that the corresponding faculty only can get access to the methods operating only on their students. That will solve this masquerading issue. Also another issue #56 has been added to keep potential adversaries away.

**Comment by bhargavajs07** [comment]
Almost fixed. Can close this after a round of testing.

**Comment by nihesh7391** [comment]
Added checks for faculty profile page..

**Comment by bhargavajs07** [comment]
Sagar already incorporated the fixes for this in the latest branch. This could be closed.
