### ISSUE TITLE
Faculty frame

### ISSUE THREAD

**Issue by nihesh7391** [s-gv/bheemboy#6]
In faculty page, faculty should get buttons for selecting Role. (Adviser/ Instructor).
For adviser role, all the advisees should appear as a button. Clicking them should either open a new page or expand into an interactive table displaying courses selected by that advisee. Clicking again should collapse the table. @sumanpanchal

**Comment by sumanpanchal** [comment]
Hi,

Added Tab button to select Adviser/Instructor roll.
Added collapse based display feature to get per Advisee course details.

Please check when you get time.

**Comment by vinkumbr** [comment]
Hi 
I have added another branch named(vinay_branch) with functionalities for approval by the instructor. We can merge the two. Yours looks aesthetically much better than mine. Have a look at this too.

**Comment by nihesh7391** [comment]
Added accept and reject button for advisor and instructor

**Comment by arthi-ramaniam** [comment]
Deleting the participant entry if the advisor rejects the course request, as it does not allow the student to re-apply
