### ISSUE TITLE
Action menu in student page should be updated after drop / credit / audit conversion is requested

### ISSUE THREAD

**Issue by s-gv** [s-gv/bheemboy#60]
After credit to audit conversion is requested, "switch to credit" option should be removed. Likewise for "request to drop" as well.

**Comment by arthi-ramaniam** [comment]
Added a "Revert option". Once A/C/Drop is chosen, request is raised. Student has the choice to revert this choice. Status shifts back to "DCC Approved" if reverted. 

Even after "DCC Approved"  A/C conversion, the choice of A/C is still open. It has to be disabled by date. There is no way to disambiguate A/C Approved and directly approved courses.
