### ISSUE TITLE
Unused states in models.py for DCC approval

### ISSUE THREAD

**Issue by arthi-ramaniam** [s-gv/bheemboy#62]
With the "OneGo" DCC approval, some of the states in models.py are not used. I ve marked the unused DCC states as "NOT USED?" @nihesh7391 Can we remove these states?

**Comment by nihesh7391** [comment]
See issue #66 for reconsidering some of the states..

**Comment by arthi-ramaniam** [comment]
Closing it as the new models.py no longer uses these limbo states.
