### ISSUE TITLE
Credit/Audit/Drop choice 

### ISSUE THREAD

**Issue by nihesh7391** [s-gv/bheemboy#8]
Workflow: Student requests to drop a course -> Adviser approves -> Instructor approves. 
If course is successfully dropped then, the course should be displayed as dropped in students page. 
similarly, student should be listed as dropped in course page.

**Comment by arthi-ramaniam** [comment]
Implemented

**Comment by nihesh7391** [comment]
Add a separate cancel button.. 
For audit/credit only the following should allowed..
Audit  -> Credit or Drop
Credit -> Audit or Drop

**Comment by arthi-ramaniam** [comment]
Audit or credit or drop conversion added. 
Once DCC approves audit/credit conversion, student table needs to be updated.

**Comment by rajeshsundaresan** [comment]
Closed since this has been implemented, checked, and pushed.
