### ISSUE TITLE
Non-RTP credit for M.Tech (Res) and Ph.D. students

### ISSUE THREAD

**Issue by rajeshsundaresan** [s-gv/bheemboy#82]
Add a non-RTP credit option for Ph.D. and M.Tech.(Res) students.
These should not contribute to CGPA.
If grade is below a threshold, they should automatically be modified to 'audit'.

**Comment by s-gv** [comment]
The new schema has a `should_count_towards_cgpa` column in the Participant table. So, the admin can set any enrollment to not be counted in CGPA calculation.

**Comment by rajeshsundaresan** [comment]
One more item to take care of while doing the enhancement. The new students have a 10-pt CGPA scale while the old students have an 8-pt CGPA scale.

**Comment by nihesh7391** [comment]
Make it student specified.

**Comment by s-gv** [comment]
What's the difference between Non-RTP credit and Audit? If there is a difference, is it enough to mark non-RTP credits to not count towards CGPA (like project credits)?

**Comment by s-gv** [comment]
Registration type is now admin controlled; the admin can add "Non-RTP Audit", "Undergrad Credit", etc.
