### ISSUE TITLE
List of few corrections needed on DCC page given by DCC

### ISSUE THREAD

**Issue by sumanpanchal** [s-gv/bheemboy#84]
List of few corrections needed on DCC pages given by DCC.
1. The list should be separate for 
   (a) MTech 1st year (b) MTech 2nd year (c) PhD (d) MTech Research
2. Name of the candidate-colour should change after registration.
3. For research students, RTP and Non RTP - consolidated credits to be indicated.
4. For MTech Students, Pool A and Pool B - consolidated credits to be indicated. 
5. For some students, Non-RTP course grades do not appear.
6. In some cases,
   for e.g. C.G.Aparna
   ? E2 202 Random Process - C grade  doesnt show C in front of it.
7. Instruction about (a) dropping the courses (b) swapping from audit <--> credit.

**Comment by bhargavajs07** [comment]
Created individual issues and assigned these items to individual contributors.

Following issues which would be enhancements or need more clarity.
4. For MTech Students, Pool A and Pool B - consolidated credits to be indicated. -- Would be an enhancement.
7. Instruction about (a) dropping the courses (b) swapping from audit <--> credit. -- Need more Clarity on this issue.
