### ISSUE TITLE
DCC Req: The list should be separate for (a) MTech 1st year (b) MTech 2nd year (c) PhD (d) MTech Research.

### ISSUE THREAD

**Issue by bhargavajs07** [s-gv/bheemboy#87]

**Comment by bhargavajs07** [comment]
Please re-assign to someone else if they have already started working on it.

**Comment by vinkumbr** [comment]
Has been incorporated. MTech 1st and 2nd year needs to be classified.

**Comment by nihesh7391** [comment]
Solved hard coding problem..
