### ISSUE TITLE
DCC Req:  Name of the candidate-colour should change after registration.

### ISSUE THREAD

**Issue by bhargavajs07** [s-gv/bheemboy#88]
Please re-assign to someone else if they have already started working on it.

**Comment by bhargavajs07** [comment]
1. Need to segregate the active students in to following categories:
      a. the DCC Approved final registrations(Students taking courses in current semester and approved by DCC) 
       b. students that were not approved by DCC(not taking any courses in current semester).

**Comment by vinkumbr** [comment]
1. Labels have been given for DCC approved final registations, DCC notified Pending requests, In progress requests etc.
   Suggestions on improvement are welcome.

**Comment by vinkumbr** [comment]
Feature implemented
