### ISSUE TITLE
Debug reported Anomalies

### ISSUE THREAD

**Issue by bhargavajs07** [s-gv/bheemboy#90]
1. For some students, Non-RTP course grades do not appear.
2. In some cases, for e.g. C.G.Aparna ? E2 202 Random Process - C grade doesnt show C in front of it.

**Comment by bhargavajs07** [comment]
Please re-assign to someone else if they have already started working on it.

**Comment by sumanpanchal** [comment]
Srinivas Murthy Sir has been resolved C.G.Aparna's grade issue.

**Comment by bhargavajs07** [comment]
1. For some students, Non-RTP course grades do not appear. Feature under development tracked in a separate issue.
