### ISSUE TITLE
Test cases for ASW 

### ISSUE THREAD

**Issue by arthi-ramaniam** [s-gv/bheemboy#95]
Take roles of 4 students, 2 advisers and instructors across department and a small test run in ASW environment.

**Comment by s-gv** [comment]
What's ASW?

**Comment by nihesh7391** [comment]
testing in AWS is done!!!

**Comment by arthi-ramaniam** [comment]
[AWS_testcases.xlsx](https://github.com/s-gv/bheemboy/files/529223/AWS_testcases.xlsx)

Basic test cases
