### ISSUE TITLE
Display project credits

### ISSUE THREAD

**Issue by arthi-ramaniam** [s-gv/bheemboy#96]
Display project credits in students/adviser (text input from student) and display credits for all courses in DCC page

**Comment by s-gv** [comment]
Credits are now displayed along with the course. Why do we need a text input?

**Comment by s-gv** [comment]
Project credits are displayed. Re-open if any other issue is present.

**Comment by arthi-ramaniam** [comment]
Text input needed for project credit details

**Comment by nihesh7391** [comment]
Not needed!!
