### ISSUE TITLE
No instructor approval needed for project

### ISSUE THREAD

**Issue by arthi-ramaniam** [s-gv/bheemboy#97]
Ideally, there is no instructor approval for project. But, in this version, "instructor pending"  appears in DCC page for courses of type project.

**Comment by s-gv** [comment]
Good catch

**Comment by arthi-ramaniam** [comment]
Instructor pending is still appearing in DCC page for project

**Comment by s-gv** [comment]
I can't reproduce this. What sequence of steps lead to this bug?

**Comment by vinkumbr** [comment]
Student - Registers for a Project type course
Advisor - Accepts registration
DCC page lists the particular advisor under 'Instructor with pending reviews' even though Project type course does not need an instructor approval.

**Comment by arthi-ramaniam** [comment]
Repetition of Issue 100. Closing it.
